# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdfu" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "286130476748a7af7fbd4a9863557949e200b40dfb53b996db44225c0622a73c"
      url "https://github.com/elicore/mdfu/releases/download/v#{version}/mdfu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6232cd227d2dfcab286beb7ed36ea050d488f2fd9419069f93fb2a25a0f136cc"
      url "https://github.com/elicore/mdfu/releases/download/v#{version}/mdfu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f71650ca49511c804154132667f6819e1aa168adfae5b637212e925af7f6c3a2"
      url "https://github.com/elicore/mdfu/releases/download/v#{version}/mdfu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5de42e262922ec8b7897098916e2b854cfe2a95a42580b8f2d7751a2e5abb322"
      url "https://github.com/elicore/mdfu/releases/download/v#{version}/mdfu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mdfu"
  desc "Fuzzy finder for Markdown notes"
  homepage "https://github.com/elicore/mdfu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdfu"

  # No zap stanza required
end
